name: Build de imagem

on:
  workflow_dispatch
#   push:
#     branches:
#       - main      

permissions:
  id-token: write   
  contents: read

jobs:
  Build_Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Autenticação AWS 
        uses: aws-actions/configure-aws-credentials@v4 
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: repo-fastapi
        run: |
          docker build -t $REGISTRY/$REPOSITORY:latest .
          docker push $REGISTRY/$REPOSITORY:latest

      - name: Deploy EC2
        uses: appleboy/ssh-action@v1.0.3
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
          REGISTRY: ${{ vars.REGISTRY }}
          REPOSITORY: ${{ vars.REPOSITORY }}
          IMAGE_TAG: ${{ vars.IMAGE_TAG }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          envs: AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_SESSION_TOKEN,AWS_REGION
          script:  |
            set -e 
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}
            docker pull ${{ steps.login-ecr.outputs.registry }}/repo-fastapi:latest
            docker stop fastapi-app || true
            docker rm fastapi-app || true
            docker run -d \
              --restart unless-stopped \
              -p 80:8000 \
              --name fastapi-app \
              ${{ steps.login-ecr.outputs.registry }}/repo-fastapi:latest
    
